version: "3.9"

services:
  test:
    image: test
    container_name: test
    build:
      context: task
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./configs:/app/configs
    networks:
      - network

  postgres:
    image: postgres:16.2-alpine
    restart: on-failure
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - network
    command: sh -c "rm -rf /docker-entrypoint-initdb.d/* && docker-entrypoint.sh postgres"

networks:
  network:
    driver: bridge
