// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import (
	entity "github.com/flew1x/ingry.tech_test_task/internal/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IBookService is an autogenerated mock type for the IBookService type
type IBookService struct {
	mock.Mock
}

// Create provides a mock function with given fields: title, author, year
func (_m *IBookService) Create(title string, author string, year uint16) (entity.Book, error) {
	ret := _m.Called(title, author, year)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, uint16) (entity.Book, error)); ok {
		return rf(title, author, year)
	}
	if rf, ok := ret.Get(0).(func(string, string, uint16) entity.Book); ok {
		r0 = rf(title, author, year)
	} else {
		r0 = ret.Get(0).(entity.Book)
	}

	if rf, ok := ret.Get(1).(func(string, string, uint16) error); ok {
		r1 = rf(title, author, year)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *IBookService) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *IBookService) GetAll() ([]entity.Book, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entity.Book
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.Book, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.Book); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Book)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *IBookService) GetByID(id uuid.UUID) (entity.Book, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 entity.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (entity.Book, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) entity.Book); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.Book)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: book
func (_m *IBookService) Update(book entity.Book) (entity.Book, error) {
	ret := _m.Called(book)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.Book) (entity.Book, error)); ok {
		return rf(book)
	}
	if rf, ok := ret.Get(0).(func(entity.Book) entity.Book); ok {
		r0 = rf(book)
	} else {
		r0 = ret.Get(0).(entity.Book)
	}

	if rf, ok := ret.Get(1).(func(entity.Book) error); ok {
		r1 = rf(book)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIBookService creates a new instance of IBookService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIBookService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IBookService {
	mock := &IBookService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
